import Layout from '@/components/layout'
import '@/global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>openTcm</title>
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
